import { Match } from './types';

export const MATCHES: Match[] = [
  {
    match_id: 'm1',
    sport: 'Football',
    league: 'La Liga',
    team_a: 'Barcelona',
    team_b: 'Real Madrid',
    start_time: '2026-04-12T20:00:00Z',
    team_a_stats: { rating: 88, wins: 22, goals_scored: 2.4, goal_diff: 28 },
    team_b_stats: { rating: 86, wins: 20, goals_scored: 2.1, goal_diff: 22 },
  },
  {
    match_id: 'm2',
    sport: 'Football',
    league: 'Premier League',
    team_a: 'Manchester City',
    team_b: 'Arsenal',
    start_time: '2026-04-13T16:30:00Z',
    team_a_stats: { rating: 90, wins: 24, goals_scored: 2.6, goal_diff: 35 },
    team_b_stats: { rating: 87, wins: 21, goals_scored: 2.2, goal_diff: 25 },
  },
  {
    match_id: 'm3',
    sport: 'Football',
    league: 'Serie A',
    team_a: 'Inter Milan',
    team_b: 'AC Milan',
    start_time: '2026-04-14T19:45:00Z',
    team_a_stats: { rating: 85, wins: 19, goals_scored: 2.0, goal_diff: 18 },
    team_b_stats: { rating: 83, wins: 17, goals_scored: 1.8, goal_diff: 14 },
  },
  {
    match_id: 'm4',
    sport: 'Football',
    league: 'Bundesliga',
    team_a: 'Bayern Munich',
    team_b: 'Borussia Dortmund',
    start_time: '2026-04-15T17:30:00Z',
    team_a_stats: { rating: 91, wins: 25, goals_scored: 2.8, goal_diff: 40 },
    team_b_stats: { rating: 84, wins: 18, goals_scored: 2.0, goal_diff: 16 },
  },
  {
    match_id: 'm5',
    sport: 'Football',
    league: 'Ligue 1',
    team_a: 'PSG',
    team_b: 'Marseille',
    start_time: '2026-04-16T20:00:00Z',
    team_a_stats: { rating: 89, wins: 23, goals_scored: 2.5, goal_diff: 32 },
    team_b_stats: { rating: 80, wins: 15, goals_scored: 1.6, goal_diff: 8 },
  },
  {
    match_id: 'm6',
    sport: 'Football',
    league: 'Premier League',
    team_a: 'Liverpool',
    team_b: 'Chelsea',
    start_time: '2026-04-17T15:00:00Z',
    team_a_stats: { rating: 87, wins: 21, goals_scored: 2.3, goal_diff: 26 },
    team_b_stats: { rating: 84, wins: 18, goals_scored: 1.9, goal_diff: 15 },
  },
  {
    match_id: 'm7',
    sport: 'Basketball',
    league: 'NBA',
    team_a: 'LA Lakers',
    team_b: 'Golden State Warriors',
    start_time: '2026-04-13T02:00:00Z',
    team_a_stats: { rating: 82, wins: 42, goals_scored: 112.5, goal_diff: 3.2 },
    team_b_stats: { rating: 85, wins: 48, goals_scored: 118.2, goal_diff: 5.8 },
  },
  {
    match_id: 'm8',
    sport: 'Basketball',
    league: 'NBA',
    team_a: 'Boston Celtics',
    team_b: 'Milwaukee Bucks',
    start_time: '2026-04-14T00:30:00Z',
    team_a_stats: { rating: 88, wins: 52, goals_scored: 120.1, goal_diff: 8.5 },
    team_b_stats: { rating: 86, wins: 49, goals_scored: 117.8, goal_diff: 6.2 },
  },
  {
    match_id: 'm9',
    sport: 'Tennis',
    league: 'ATP Masters',
    team_a: 'Carlos Alcaraz',
    team_b: 'Jannik Sinner',
    start_time: '2026-04-12T14:00:00Z',
    team_a_stats: { rating: 92, wins: 35, goals_scored: 6.8, goal_diff: 2.1 },
    team_b_stats: { rating: 91, wins: 34, goals_scored: 6.7, goal_diff: 2.0 },
  },
  {
    match_id: 'm10',
    sport: 'Football',
    league: 'La Liga',
    team_a: 'Atletico Madrid',
    team_b: 'Sevilla',
    start_time: '2026-04-18T18:00:00Z',
    team_a_stats: { rating: 83, wins: 17, goals_scored: 1.7, goal_diff: 12 },
    team_b_stats: { rating: 76, wins: 12, goals_scored: 1.3, goal_diff: 2 },
  },
];
